Vagrant.configure(2) do |config|
    config.vm.box = "generic/debian10"
    config.vm.box_version = "2.0.6"
    config.vm.define "kvmi"

    config.vm.synced_folder ".", "/vagrant", disabled: true

    root_dir = '/vagrant'
    # NFS only works with libvirt
    config.vm.synced_folder "..", root_dir

    config.vm.provider "libvirt" do |libvirt, override|
        libvirt.cpus = 4
        libvirt.memory = 2048
        libvirt.nic_model_type = "virtio"
        libvirt.driver = "kvm"
        libvirt.nested = true

        # use NFS
        override.vm.synced_folder "..", root_dir,
            :nfs => true,
            :nfs_version => 4,
            :nfs_udp => false,
            # speedup NFS with custom options
            :linux__nfs_options => ["rw", "no_subtree_check", "all_squash", "async"]
    end

    config.vm.provider "virtualbox" do |vbox, override|
        vbox.cpus = 4
        vbox.memory = 2048
        vbox.linked_clone = true

        # virtualbox needs specific config for NFS, use vboxsf instead
        override.vm.synced_folder "..", root_dir,
            :type => "virtualbox"
    end

    config.vm.provision "ansible" do |ansible|
        # debug
        # ansible.verbose =  '-vvv'
        # ansible.start_at_task =  ''
        ansible.playbook = "ansible/playbook_1.yml"
        ansible.extra_vars = {
            'root_dir': root_dir,
        }
    end

    config.vm.provision "reload"

    config.vm.provision "ansible" do |ansible|
        # debug
        # ansible.verbose =  '-vvv'
        # ansible.start_at_task =  ''
        ansible.playbook = "ansible/playbook_2.yml"
        ansible.extra_vars = {
            'root_dir': root_dir,
        }
    end
end
