---
- hosts: all
  become: true
  vars:
    # download the VM image instead of building it with Packer, if available
    download_vm_image: false
  pre_tasks:
    - name: get kernel version
      command: uname -r
      register: uname

    - name: display kernel version
      debug:
        var: uname.stdout

    - name: disable singlestep test
      command: sed -e '/test_cmd_vcpu_control_singlestep(vm);/d' -i {{ root_dir }}/kvm/tools/testing/selftests/kvm/x86_64/kvmi_test.c

    - name: compile kvm self-tests
      make:
        chdir: "{{ root_dir }}/kvm/tools/testing/selftests/kvm"
        target: all
        params:
          TEST_GEN_PROGS_x86_64: x86_64/kvmi_test
          DEBUG: 1
      become: false

    - name: run kvm self-tests
      command: ./tools/testing/selftests/kvm/x86_64/kvmi_test
      args:
        chdir: "{{ root_dir }}/kvm"

  roles:
    - remote
    - qemu
    - libvmi
    - vm
